name = "pico_examples"
description = "Examples for Ada on the Raspberry Pi Pico"
version = "0.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = ["BSD 3-Clauses"]
project-files = ["blink/blink.gpr"]
tags = ["embedded", "nostd", "pico", "rp2040"]
auto-gpr-with=false

executables = ["pico_examples"]

[[depends-on]]
pico_bsp = "^0.1.0"
